/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        body: ["var(--font-manrope)", "system-ui", "sans-serif"],
        display: ["var(--font-instrument-serif)", "Georgia", "serif"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        warm: {
          50: "#faf9f7",
          100: "#f5f3ef",
          200: "#ebe7e0",
          300: "#d9d3c9",
          400: "#b8ae9f",
          500: "#968a78",
          600: "#7a6e5d",
          700: "#5c5248",
          800: "#3d3632",
          900: "#1a1a18",
        },
        terracotta: {
          DEFAULT: "#c2491d",
          light: "#e07a52",
          dark: "#9a3a17",
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          "color-scheme": "light",
          primary: "#c2491d",
          "primary-content": "#ffffff",
          secondary: "#6b5c4d",
          "secondary-content": "#ffffff",
          accent: "#3d7a6a",
          "accent-content": "#ffffff",
          neutral: "#1a1a18",
          "neutral-content": "#faf9f7",
          "base-100": "#ffffff",
          "base-200": "#faf9f7",
          "base-300": "#f0ede8",
          "base-content": "#1a1a18",
          info: "#3b82f6",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1rem",
        },
      },
      {
        dark: {
          "color-scheme": "dark",
          primary: "#e07a52",
          "primary-content": "#1a1a18",
          secondary: "#a89383",
          "secondary-content": "#1a1a18",
          accent: "#5eb8a3",
          "accent-content": "#1a1a18",
          neutral: "#e8e6e1",
          "neutral-content": "#1a1a18",
          "base-100": "#1c1c1a",
          "base-200": "#141413",
          "base-300": "#2a2a28",
          "base-content": "#e8e6e1",
          info: "#60a5fa",
          success: "#4ade80",
          warning: "#fbbf24",
          error: "#f87171",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1rem",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: false,
    themeRoot: ":root",
  },
};
